// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/galaxsync-redesign/AppleInspired.tsx": () => import("../components/mockups/galaxsync-redesign/AppleInspired.tsx"),
  "./components/mockups/ruhaus-homepage/DarkStudio.tsx": () => import("../components/mockups/ruhaus-homepage/DarkStudio.tsx"),
  "./components/mockups/ruhaus-homepage/PlayfulInnovation.tsx": () => import("../components/mockups/ruhaus-homepage/PlayfulInnovation.tsx"),
  "./components/mockups/ruhaus-homepage/WarmEditorial.tsx": () => import("../components/mockups/ruhaus-homepage/WarmEditorial.tsx")
};
